package model;
// Generated Feb 11, 2018 2:03:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articles generated by hbm2java
 */
public class Articles  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String title;
     private String text;
     private int private_;
     private Integer seen;
     private String setupTime;
     private String image;
     private Set tipArticles = new HashSet(0);
     private Set commentses = new HashSet(0);
     private Set likeses = new HashSet(0);
     private Set seenArticleses = new HashSet(0);

    public Articles() {
    }

	
    public Articles(String title, String text, int private_, String setupTime) {
        this.title = title;
        this.text = text;
        this.private_ = private_;
        this.setupTime = setupTime;
    }
    public Articles(Users users, String title, String text, int private_, Integer seen, String setupTime, String image, Set tipArticles, Set commentses, Set likeses, Set seenArticleses) {
       this.users = users;
       this.title = title;
       this.text = text;
       this.private_ = private_;
       this.seen = seen;
       this.setupTime = setupTime;
       this.image = image;
       this.tipArticles = tipArticles;
       this.commentses = commentses;
       this.likeses = likeses;
       this.seenArticleses = seenArticleses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public int getPrivate_() {
        return this.private_;
    }
    
    public void setPrivate_(int private_) {
        this.private_ = private_;
    }
    public Integer getSeen() {
        return this.seen;
    }
    
    public void setSeen(Integer seen) {
        this.seen = seen;
    }
    public String getSetupTime() {
        return this.setupTime;
    }
    
    public void setSetupTime(String setupTime) {
        this.setupTime = setupTime;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getTipArticles() {
        return this.tipArticles;
    }
    
    public void setTipArticles(Set tipArticles) {
        this.tipArticles = tipArticles;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getLikeses() {
        return this.likeses;
    }
    
    public void setLikeses(Set likeses) {
        this.likeses = likeses;
    }
    public Set getSeenArticleses() {
        return this.seenArticleses;
    }
    
    public void setSeenArticleses(Set seenArticleses) {
        this.seenArticleses = seenArticleses;
    }




}


