package model;
// Generated Feb 11, 2018 2:03:32 PM by Hibernate Tools 4.3.1



/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String name;
     private String description;
     private String dateWhenOpened;
     private String image;

    public Company() {
    }

    public Company(Users users, String name, String description, String dateWhenOpened, String image) {
       this.users = users;
       this.name = name;
       this.description = description;
       this.dateWhenOpened = dateWhenOpened;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDateWhenOpened() {
        return this.dateWhenOpened;
    }
    
    public void setDateWhenOpened(String dateWhenOpened) {
        this.dateWhenOpened = dateWhenOpened;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


