package model;
// Generated Feb 11, 2018 2:03:32 PM by Hibernate Tools 4.3.1



/**
 * ImageArticle generated by hbm2java
 */
public class ImageArticle  implements java.io.Serializable {


     private Integer id;
     private Integer idOfArticle;
     private Integer idIfImage;

    public ImageArticle() {
    }

    public ImageArticle(Integer idOfArticle, Integer idIfImage) {
       this.idOfArticle = idOfArticle;
       this.idIfImage = idIfImage;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdOfArticle() {
        return this.idOfArticle;
    }
    
    public void setIdOfArticle(Integer idOfArticle) {
        this.idOfArticle = idOfArticle;
    }
    public Integer getIdIfImage() {
        return this.idIfImage;
    }
    
    public void setIdIfImage(Integer idIfImage) {
        this.idIfImage = idIfImage;
    }




}


