package model;
// Generated Feb 11, 2018 2:03:32 PM by Hibernate Tools 4.3.1



/**
 * Likes generated by hbm2java
 */
public class Likes  implements java.io.Serializable {


     private Integer id;
     private Articles articles;
     private Users users;
     private String time;

    public Likes() {
    }

    public Likes(Articles articles, Users users, String time) {
       this.articles = articles;
       this.users = users;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Articles getArticles() {
        return this.articles;
    }
    
    public void setArticles(Articles articles) {
        this.articles = articles;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }




}


