package model;
// Generated Feb 11, 2018 2:03:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subtopics generated by hbm2java
 */
public class Subtopics  implements java.io.Serializable {


     private Integer id;
     private String subtopic;
     private Set userSubtopics = new HashSet(0);

    public Subtopics() {
    }

    public Subtopics(String subtopic, Set userSubtopics) {
       this.subtopic = subtopic;
       this.userSubtopics = userSubtopics;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSubtopic() {
        return this.subtopic;
    }
    
    public void setSubtopic(String subtopic) {
        this.subtopic = subtopic;
    }
    public Set getUserSubtopics() {
        return this.userSubtopics;
    }
    
    public void setUserSubtopics(Set userSubtopics) {
        this.userSubtopics = userSubtopics;
    }




}


