package model;
// Generated Feb 11, 2018 2:03:32 PM by Hibernate Tools 4.3.1



/**
 * TipArticle generated by hbm2java
 */
public class TipArticle  implements java.io.Serializable {


     private Integer id;
     private Articles articles;
     private Tips tips;

    public TipArticle() {
    }

    public TipArticle(Articles articles, Tips tips) {
       this.articles = articles;
       this.tips = tips;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Articles getArticles() {
        return this.articles;
    }
    
    public void setArticles(Articles articles) {
        this.articles = articles;
    }
    public Tips getTips() {
        return this.tips;
    }
    
    public void setTips(Tips tips) {
        this.tips = tips;
    }




}


