package model;
// Generated Feb 11, 2018 2:03:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Topics generated by hbm2java
 */
public class Topics  implements java.io.Serializable {


     private Integer id;
     private String topic;
     private Set userTopics = new HashSet(0);

    public Topics() {
    }

	
    public Topics(String topic) {
        this.topic = topic;
    }
    public Topics(String topic, Set userTopics) {
       this.topic = topic;
       this.userTopics = userTopics;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public Set getUserTopics() {
        return this.userTopics;
    }
    
    public void setUserTopics(Set userTopics) {
        this.userTopics = userTopics;
    }




}


