package model;
// Generated Feb 11, 2018 2:03:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private int companyId;
     private String city;
     private String country;
     private String jobTitle;
     private String email;
     private String password;
     private String library;
     private Set likeses = new HashSet(0);
     private Set seenArticleses = new HashSet(0);
     private Set userTopics = new HashSet(0);
     private Set userSubtopics = new HashSet(0);
     private Set commentses = new HashSet(0);
     private Set articleses = new HashSet(0);
     private Set companies = new HashSet(0);

    public Users() {
    }

	
    public Users(String firstName, String lastName, int companyId, String city, String country, String jobTitle, String email, String password, String library) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.companyId = companyId;
        this.city = city;
        this.country = country;
        this.jobTitle = jobTitle;
        this.email = email;
        this.password = password;
        this.library = library;
    }
    public Users(String firstName, String lastName, int companyId, String city, String country, String jobTitle, String email, String password, String library, Set likeses, Set seenArticleses, Set userTopics, Set userSubtopics, Set commentses, Set articleses, Set companies) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.companyId = companyId;
       this.city = city;
       this.country = country;
       this.jobTitle = jobTitle;
       this.email = email;
       this.password = password;
       this.library = library;
       this.likeses = likeses;
       this.seenArticleses = seenArticleses;
       this.userTopics = userTopics;
       this.userSubtopics = userSubtopics;
       this.commentses = commentses;
       this.articleses = articleses;
       this.companies = companies;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLibrary() {
        return this.library;
    }
    
    public void setLibrary(String library) {
        this.library = library;
    }
    public Set getLikeses() {
        return this.likeses;
    }
    
    public void setLikeses(Set likeses) {
        this.likeses = likeses;
    }
    public Set getSeenArticleses() {
        return this.seenArticleses;
    }
    
    public void setSeenArticleses(Set seenArticleses) {
        this.seenArticleses = seenArticleses;
    }
    public Set getUserTopics() {
        return this.userTopics;
    }
    
    public void setUserTopics(Set userTopics) {
        this.userTopics = userTopics;
    }
    public Set getUserSubtopics() {
        return this.userSubtopics;
    }
    
    public void setUserSubtopics(Set userSubtopics) {
        this.userSubtopics = userSubtopics;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getArticleses() {
        return this.articleses;
    }
    
    public void setArticleses(Set articleses) {
        this.articleses = articleses;
    }
    public Set getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set companies) {
        this.companies = companies;
    }




}


